#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ComboBox;
                ref class Button;
                ref class TextBlock;
                ref class Canvas;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Polyline;
            }
        }
    }
}

namespace GettingData
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::ComboBox^ muse_list_combobox;
        private: ::Windows::UI::Xaml::Controls::Button^ refresh_button;
        private: ::Windows::UI::Xaml::Controls::Button^ connect_button;
        private: ::Windows::UI::Xaml::Controls::Button^ disconnect_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ jd_title;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ connection_status_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ connection_status;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ data_type_combobox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ version_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ version;
        private: ::Windows::UI::Xaml::Controls::Button^ pause_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_1_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_1_data;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_2_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_2_data;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_3_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_3_data;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_4_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_4_data;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_5_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_5_data;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_6_label;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ line_6_data;
        private: ::Windows::UI::Xaml::Controls::Canvas^ GraphCanvas;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline2;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline3;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline4;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline5;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ DataPolyline6;
    };
}

