// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_Management_Update_2_H
#define WINRT_Windows_Management_Update_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Management.Update.1.h"
WINRT_EXPORT namespace winrt::Windows::Management::Update
{
    struct __declspec(empty_bases) PreviewBuildsManager : winrt::Windows::Management::Update::IPreviewBuildsManager
    {
        PreviewBuildsManager(std::nullptr_t) noexcept {}
        PreviewBuildsManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IPreviewBuildsManager(ptr, take_ownership_from_abi) {}
        PreviewBuildsManager(PreviewBuildsManager const&) noexcept = default;
        PreviewBuildsManager(PreviewBuildsManager&&) noexcept = default;
        PreviewBuildsManager& operator=(PreviewBuildsManager const&) & noexcept = default;
        PreviewBuildsManager& operator=(PreviewBuildsManager&&) & noexcept = default;
        static auto GetDefault();
        static auto IsSupported();
    };
    struct __declspec(empty_bases) PreviewBuildsState : winrt::Windows::Management::Update::IPreviewBuildsState
    {
        PreviewBuildsState(std::nullptr_t) noexcept {}
        PreviewBuildsState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IPreviewBuildsState(ptr, take_ownership_from_abi) {}
        PreviewBuildsState(PreviewBuildsState const&) noexcept = default;
        PreviewBuildsState(PreviewBuildsState&&) noexcept = default;
        PreviewBuildsState& operator=(PreviewBuildsState const&) & noexcept = default;
        PreviewBuildsState& operator=(PreviewBuildsState&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdate : winrt::Windows::Management::Update::IWindowsUpdate
    {
        WindowsUpdate(std::nullptr_t) noexcept {}
        WindowsUpdate(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdate(ptr, take_ownership_from_abi) {}
        WindowsUpdate(WindowsUpdate const&) noexcept = default;
        WindowsUpdate(WindowsUpdate&&) noexcept = default;
        WindowsUpdate& operator=(WindowsUpdate const&) & noexcept = default;
        WindowsUpdate& operator=(WindowsUpdate&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateActionCompletedEventArgs : winrt::Windows::Management::Update::IWindowsUpdateActionCompletedEventArgs
    {
        WindowsUpdateActionCompletedEventArgs(std::nullptr_t) noexcept {}
        WindowsUpdateActionCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateActionCompletedEventArgs(ptr, take_ownership_from_abi) {}
        WindowsUpdateActionCompletedEventArgs(WindowsUpdateActionCompletedEventArgs const&) noexcept = default;
        WindowsUpdateActionCompletedEventArgs(WindowsUpdateActionCompletedEventArgs&&) noexcept = default;
        WindowsUpdateActionCompletedEventArgs& operator=(WindowsUpdateActionCompletedEventArgs const&) & noexcept = default;
        WindowsUpdateActionCompletedEventArgs& operator=(WindowsUpdateActionCompletedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateActionProgress : winrt::Windows::Management::Update::IWindowsUpdateActionProgress
    {
        WindowsUpdateActionProgress(std::nullptr_t) noexcept {}
        WindowsUpdateActionProgress(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateActionProgress(ptr, take_ownership_from_abi) {}
        WindowsUpdateActionProgress(WindowsUpdateActionProgress const&) noexcept = default;
        WindowsUpdateActionProgress(WindowsUpdateActionProgress&&) noexcept = default;
        WindowsUpdateActionProgress& operator=(WindowsUpdateActionProgress const&) & noexcept = default;
        WindowsUpdateActionProgress& operator=(WindowsUpdateActionProgress&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateActionResult : winrt::Windows::Management::Update::IWindowsUpdateActionResult
    {
        WindowsUpdateActionResult(std::nullptr_t) noexcept {}
        WindowsUpdateActionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateActionResult(ptr, take_ownership_from_abi) {}
        WindowsUpdateActionResult(WindowsUpdateActionResult const&) noexcept = default;
        WindowsUpdateActionResult(WindowsUpdateActionResult&&) noexcept = default;
        WindowsUpdateActionResult& operator=(WindowsUpdateActionResult const&) & noexcept = default;
        WindowsUpdateActionResult& operator=(WindowsUpdateActionResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateAdministrator : winrt::Windows::Management::Update::IWindowsUpdateAdministrator
    {
        WindowsUpdateAdministrator(std::nullptr_t) noexcept {}
        WindowsUpdateAdministrator(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateAdministrator(ptr, take_ownership_from_abi) {}
        WindowsUpdateAdministrator(WindowsUpdateAdministrator const&) noexcept = default;
        WindowsUpdateAdministrator(WindowsUpdateAdministrator&&) noexcept = default;
        WindowsUpdateAdministrator& operator=(WindowsUpdateAdministrator const&) & noexcept = default;
        WindowsUpdateAdministrator& operator=(WindowsUpdateAdministrator&&) & noexcept = default;
        static auto GetRegisteredAdministrator(param::hstring const& organizationName);
        static auto RegisterForAdministration(param::hstring const& organizationName, winrt::Windows::Management::Update::WindowsUpdateAdministratorOptions const& options);
        static auto UnregisterForAdministration(param::hstring const& organizationName);
        static auto GetRegisteredAdministratorName();
        static auto RequestRestart(winrt::Windows::Management::Update::WindowsUpdateRestartRequestOptions const& restartOptions);
        static auto CancelRestartRequest(param::hstring const& requestRestartToken);
    };
    struct __declspec(empty_bases) WindowsUpdateApprovalData : winrt::Windows::Management::Update::IWindowsUpdateApprovalData
    {
        WindowsUpdateApprovalData(std::nullptr_t) noexcept {}
        WindowsUpdateApprovalData(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateApprovalData(ptr, take_ownership_from_abi) {}
        WindowsUpdateApprovalData();
        WindowsUpdateApprovalData(WindowsUpdateApprovalData const&) noexcept = default;
        WindowsUpdateApprovalData(WindowsUpdateApprovalData&&) noexcept = default;
        WindowsUpdateApprovalData& operator=(WindowsUpdateApprovalData const&) & noexcept = default;
        WindowsUpdateApprovalData& operator=(WindowsUpdateApprovalData&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateAttentionRequiredInfo : winrt::Windows::Management::Update::IWindowsUpdateAttentionRequiredInfo
    {
        WindowsUpdateAttentionRequiredInfo(std::nullptr_t) noexcept {}
        WindowsUpdateAttentionRequiredInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateAttentionRequiredInfo(ptr, take_ownership_from_abi) {}
        WindowsUpdateAttentionRequiredInfo(WindowsUpdateAttentionRequiredInfo const&) noexcept = default;
        WindowsUpdateAttentionRequiredInfo(WindowsUpdateAttentionRequiredInfo&&) noexcept = default;
        WindowsUpdateAttentionRequiredInfo& operator=(WindowsUpdateAttentionRequiredInfo const&) & noexcept = default;
        WindowsUpdateAttentionRequiredInfo& operator=(WindowsUpdateAttentionRequiredInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateAttentionRequiredReasonChangedEventArgs : winrt::Windows::Management::Update::IWindowsUpdateAttentionRequiredReasonChangedEventArgs
    {
        WindowsUpdateAttentionRequiredReasonChangedEventArgs(std::nullptr_t) noexcept {}
        WindowsUpdateAttentionRequiredReasonChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateAttentionRequiredReasonChangedEventArgs(ptr, take_ownership_from_abi) {}
        WindowsUpdateAttentionRequiredReasonChangedEventArgs(WindowsUpdateAttentionRequiredReasonChangedEventArgs const&) noexcept = default;
        WindowsUpdateAttentionRequiredReasonChangedEventArgs(WindowsUpdateAttentionRequiredReasonChangedEventArgs&&) noexcept = default;
        WindowsUpdateAttentionRequiredReasonChangedEventArgs& operator=(WindowsUpdateAttentionRequiredReasonChangedEventArgs const&) & noexcept = default;
        WindowsUpdateAttentionRequiredReasonChangedEventArgs& operator=(WindowsUpdateAttentionRequiredReasonChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateGetAdministratorResult : winrt::Windows::Management::Update::IWindowsUpdateGetAdministratorResult
    {
        WindowsUpdateGetAdministratorResult(std::nullptr_t) noexcept {}
        WindowsUpdateGetAdministratorResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateGetAdministratorResult(ptr, take_ownership_from_abi) {}
        WindowsUpdateGetAdministratorResult(WindowsUpdateGetAdministratorResult const&) noexcept = default;
        WindowsUpdateGetAdministratorResult(WindowsUpdateGetAdministratorResult&&) noexcept = default;
        WindowsUpdateGetAdministratorResult& operator=(WindowsUpdateGetAdministratorResult const&) & noexcept = default;
        WindowsUpdateGetAdministratorResult& operator=(WindowsUpdateGetAdministratorResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateItem : winrt::Windows::Management::Update::IWindowsUpdateItem
    {
        WindowsUpdateItem(std::nullptr_t) noexcept {}
        WindowsUpdateItem(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateItem(ptr, take_ownership_from_abi) {}
        WindowsUpdateItem(WindowsUpdateItem const&) noexcept = default;
        WindowsUpdateItem(WindowsUpdateItem&&) noexcept = default;
        WindowsUpdateItem& operator=(WindowsUpdateItem const&) & noexcept = default;
        WindowsUpdateItem& operator=(WindowsUpdateItem&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateManager : winrt::Windows::Management::Update::IWindowsUpdateManager
    {
        WindowsUpdateManager(std::nullptr_t) noexcept {}
        WindowsUpdateManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateManager(ptr, take_ownership_from_abi) {}
        explicit WindowsUpdateManager(param::hstring const& clientId);
        WindowsUpdateManager(WindowsUpdateManager const&) noexcept = default;
        WindowsUpdateManager(WindowsUpdateManager&&) noexcept = default;
        WindowsUpdateManager& operator=(WindowsUpdateManager const&) & noexcept = default;
        WindowsUpdateManager& operator=(WindowsUpdateManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateProgressChangedEventArgs : winrt::Windows::Management::Update::IWindowsUpdateProgressChangedEventArgs
    {
        WindowsUpdateProgressChangedEventArgs(std::nullptr_t) noexcept {}
        WindowsUpdateProgressChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateProgressChangedEventArgs(ptr, take_ownership_from_abi) {}
        WindowsUpdateProgressChangedEventArgs(WindowsUpdateProgressChangedEventArgs const&) noexcept = default;
        WindowsUpdateProgressChangedEventArgs(WindowsUpdateProgressChangedEventArgs&&) noexcept = default;
        WindowsUpdateProgressChangedEventArgs& operator=(WindowsUpdateProgressChangedEventArgs const&) & noexcept = default;
        WindowsUpdateProgressChangedEventArgs& operator=(WindowsUpdateProgressChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateRestartRequestOptions : winrt::Windows::Management::Update::IWindowsUpdateRestartRequestOptions
    {
        WindowsUpdateRestartRequestOptions(std::nullptr_t) noexcept {}
        WindowsUpdateRestartRequestOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateRestartRequestOptions(ptr, take_ownership_from_abi) {}
        WindowsUpdateRestartRequestOptions();
        WindowsUpdateRestartRequestOptions(param::hstring const& title, param::hstring const& description, winrt::Windows::Foundation::Uri const& moreInfoUrl, int32_t complianceDeadlineInDays, int32_t complianceGracePeriodInDays);
        WindowsUpdateRestartRequestOptions(WindowsUpdateRestartRequestOptions const&) noexcept = default;
        WindowsUpdateRestartRequestOptions(WindowsUpdateRestartRequestOptions&&) noexcept = default;
        WindowsUpdateRestartRequestOptions& operator=(WindowsUpdateRestartRequestOptions const&) & noexcept = default;
        WindowsUpdateRestartRequestOptions& operator=(WindowsUpdateRestartRequestOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WindowsUpdateScanCompletedEventArgs : winrt::Windows::Management::Update::IWindowsUpdateScanCompletedEventArgs
    {
        WindowsUpdateScanCompletedEventArgs(std::nullptr_t) noexcept {}
        WindowsUpdateScanCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Management::Update::IWindowsUpdateScanCompletedEventArgs(ptr, take_ownership_from_abi) {}
        WindowsUpdateScanCompletedEventArgs(WindowsUpdateScanCompletedEventArgs const&) noexcept = default;
        WindowsUpdateScanCompletedEventArgs(WindowsUpdateScanCompletedEventArgs&&) noexcept = default;
        WindowsUpdateScanCompletedEventArgs& operator=(WindowsUpdateScanCompletedEventArgs const&) & noexcept = default;
        WindowsUpdateScanCompletedEventArgs& operator=(WindowsUpdateScanCompletedEventArgs&&) & noexcept = default;
    };
}
#endif
