// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_Management_Update_1_H
#define WINRT_Windows_Management_Update_1_H
#include "winrt/impl/Windows.Management.Update.0.h"
WINRT_EXPORT namespace winrt::Windows::Management::Update
{
    struct __declspec(empty_bases) IPreviewBuildsManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsManager>
    {
        IPreviewBuildsManager(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPreviewBuildsManager(IPreviewBuildsManager const&) noexcept = default;
        IPreviewBuildsManager(IPreviewBuildsManager&&) noexcept = default;
        IPreviewBuildsManager& operator=(IPreviewBuildsManager const&) & noexcept = default;
        IPreviewBuildsManager& operator=(IPreviewBuildsManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPreviewBuildsManagerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsManagerStatics>
    {
        IPreviewBuildsManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPreviewBuildsManagerStatics(IPreviewBuildsManagerStatics const&) noexcept = default;
        IPreviewBuildsManagerStatics(IPreviewBuildsManagerStatics&&) noexcept = default;
        IPreviewBuildsManagerStatics& operator=(IPreviewBuildsManagerStatics const&) & noexcept = default;
        IPreviewBuildsManagerStatics& operator=(IPreviewBuildsManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPreviewBuildsState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsState>
    {
        IPreviewBuildsState(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPreviewBuildsState(IPreviewBuildsState const&) noexcept = default;
        IPreviewBuildsState(IPreviewBuildsState&&) noexcept = default;
        IPreviewBuildsState& operator=(IPreviewBuildsState const&) & noexcept = default;
        IPreviewBuildsState& operator=(IPreviewBuildsState&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdate :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdate>
    {
        IWindowsUpdate(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdate(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdate(IWindowsUpdate const&) noexcept = default;
        IWindowsUpdate(IWindowsUpdate&&) noexcept = default;
        IWindowsUpdate& operator=(IWindowsUpdate const&) & noexcept = default;
        IWindowsUpdate& operator=(IWindowsUpdate&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateActionCompletedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionCompletedEventArgs>
    {
        IWindowsUpdateActionCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateActionCompletedEventArgs(IWindowsUpdateActionCompletedEventArgs const&) noexcept = default;
        IWindowsUpdateActionCompletedEventArgs(IWindowsUpdateActionCompletedEventArgs&&) noexcept = default;
        IWindowsUpdateActionCompletedEventArgs& operator=(IWindowsUpdateActionCompletedEventArgs const&) & noexcept = default;
        IWindowsUpdateActionCompletedEventArgs& operator=(IWindowsUpdateActionCompletedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateActionProgress :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionProgress>
    {
        IWindowsUpdateActionProgress(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionProgress(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateActionProgress(IWindowsUpdateActionProgress const&) noexcept = default;
        IWindowsUpdateActionProgress(IWindowsUpdateActionProgress&&) noexcept = default;
        IWindowsUpdateActionProgress& operator=(IWindowsUpdateActionProgress const&) & noexcept = default;
        IWindowsUpdateActionProgress& operator=(IWindowsUpdateActionProgress&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateActionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionResult>
    {
        IWindowsUpdateActionResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateActionResult(IWindowsUpdateActionResult const&) noexcept = default;
        IWindowsUpdateActionResult(IWindowsUpdateActionResult&&) noexcept = default;
        IWindowsUpdateActionResult& operator=(IWindowsUpdateActionResult const&) & noexcept = default;
        IWindowsUpdateActionResult& operator=(IWindowsUpdateActionResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateAdministrator :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAdministrator>
    {
        IWindowsUpdateAdministrator(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAdministrator(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateAdministrator(IWindowsUpdateAdministrator const&) noexcept = default;
        IWindowsUpdateAdministrator(IWindowsUpdateAdministrator&&) noexcept = default;
        IWindowsUpdateAdministrator& operator=(IWindowsUpdateAdministrator const&) & noexcept = default;
        IWindowsUpdateAdministrator& operator=(IWindowsUpdateAdministrator&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateAdministratorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAdministratorStatics>
    {
        IWindowsUpdateAdministratorStatics(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAdministratorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateAdministratorStatics(IWindowsUpdateAdministratorStatics const&) noexcept = default;
        IWindowsUpdateAdministratorStatics(IWindowsUpdateAdministratorStatics&&) noexcept = default;
        IWindowsUpdateAdministratorStatics& operator=(IWindowsUpdateAdministratorStatics const&) & noexcept = default;
        IWindowsUpdateAdministratorStatics& operator=(IWindowsUpdateAdministratorStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateApprovalData :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateApprovalData>
    {
        IWindowsUpdateApprovalData(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateApprovalData(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateApprovalData(IWindowsUpdateApprovalData const&) noexcept = default;
        IWindowsUpdateApprovalData(IWindowsUpdateApprovalData&&) noexcept = default;
        IWindowsUpdateApprovalData& operator=(IWindowsUpdateApprovalData const&) & noexcept = default;
        IWindowsUpdateApprovalData& operator=(IWindowsUpdateApprovalData&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateAttentionRequiredInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAttentionRequiredInfo>
    {
        IWindowsUpdateAttentionRequiredInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAttentionRequiredInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateAttentionRequiredInfo(IWindowsUpdateAttentionRequiredInfo const&) noexcept = default;
        IWindowsUpdateAttentionRequiredInfo(IWindowsUpdateAttentionRequiredInfo&&) noexcept = default;
        IWindowsUpdateAttentionRequiredInfo& operator=(IWindowsUpdateAttentionRequiredInfo const&) & noexcept = default;
        IWindowsUpdateAttentionRequiredInfo& operator=(IWindowsUpdateAttentionRequiredInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateAttentionRequiredReasonChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAttentionRequiredReasonChangedEventArgs>
    {
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(IWindowsUpdateAttentionRequiredReasonChangedEventArgs const&) noexcept = default;
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(IWindowsUpdateAttentionRequiredReasonChangedEventArgs&&) noexcept = default;
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs& operator=(IWindowsUpdateAttentionRequiredReasonChangedEventArgs const&) & noexcept = default;
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs& operator=(IWindowsUpdateAttentionRequiredReasonChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateGetAdministratorResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateGetAdministratorResult>
    {
        IWindowsUpdateGetAdministratorResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateGetAdministratorResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateGetAdministratorResult(IWindowsUpdateGetAdministratorResult const&) noexcept = default;
        IWindowsUpdateGetAdministratorResult(IWindowsUpdateGetAdministratorResult&&) noexcept = default;
        IWindowsUpdateGetAdministratorResult& operator=(IWindowsUpdateGetAdministratorResult const&) & noexcept = default;
        IWindowsUpdateGetAdministratorResult& operator=(IWindowsUpdateGetAdministratorResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateItem :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateItem>
    {
        IWindowsUpdateItem(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateItem(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateItem(IWindowsUpdateItem const&) noexcept = default;
        IWindowsUpdateItem(IWindowsUpdateItem&&) noexcept = default;
        IWindowsUpdateItem& operator=(IWindowsUpdateItem const&) & noexcept = default;
        IWindowsUpdateItem& operator=(IWindowsUpdateItem&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManager>
    {
        IWindowsUpdateManager(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateManager(IWindowsUpdateManager const&) noexcept = default;
        IWindowsUpdateManager(IWindowsUpdateManager&&) noexcept = default;
        IWindowsUpdateManager& operator=(IWindowsUpdateManager const&) & noexcept = default;
        IWindowsUpdateManager& operator=(IWindowsUpdateManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManagerFactory>
    {
        IWindowsUpdateManagerFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateManagerFactory(IWindowsUpdateManagerFactory const&) noexcept = default;
        IWindowsUpdateManagerFactory(IWindowsUpdateManagerFactory&&) noexcept = default;
        IWindowsUpdateManagerFactory& operator=(IWindowsUpdateManagerFactory const&) & noexcept = default;
        IWindowsUpdateManagerFactory& operator=(IWindowsUpdateManagerFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateProgressChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateProgressChangedEventArgs>
    {
        IWindowsUpdateProgressChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateProgressChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateProgressChangedEventArgs(IWindowsUpdateProgressChangedEventArgs const&) noexcept = default;
        IWindowsUpdateProgressChangedEventArgs(IWindowsUpdateProgressChangedEventArgs&&) noexcept = default;
        IWindowsUpdateProgressChangedEventArgs& operator=(IWindowsUpdateProgressChangedEventArgs const&) & noexcept = default;
        IWindowsUpdateProgressChangedEventArgs& operator=(IWindowsUpdateProgressChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateRestartRequestOptions :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateRestartRequestOptions>
    {
        IWindowsUpdateRestartRequestOptions(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateRestartRequestOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateRestartRequestOptions(IWindowsUpdateRestartRequestOptions const&) noexcept = default;
        IWindowsUpdateRestartRequestOptions(IWindowsUpdateRestartRequestOptions&&) noexcept = default;
        IWindowsUpdateRestartRequestOptions& operator=(IWindowsUpdateRestartRequestOptions const&) & noexcept = default;
        IWindowsUpdateRestartRequestOptions& operator=(IWindowsUpdateRestartRequestOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateRestartRequestOptionsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateRestartRequestOptionsFactory>
    {
        IWindowsUpdateRestartRequestOptionsFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateRestartRequestOptionsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateRestartRequestOptionsFactory(IWindowsUpdateRestartRequestOptionsFactory const&) noexcept = default;
        IWindowsUpdateRestartRequestOptionsFactory(IWindowsUpdateRestartRequestOptionsFactory&&) noexcept = default;
        IWindowsUpdateRestartRequestOptionsFactory& operator=(IWindowsUpdateRestartRequestOptionsFactory const&) & noexcept = default;
        IWindowsUpdateRestartRequestOptionsFactory& operator=(IWindowsUpdateRestartRequestOptionsFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWindowsUpdateScanCompletedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateScanCompletedEventArgs>
    {
        IWindowsUpdateScanCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateScanCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWindowsUpdateScanCompletedEventArgs(IWindowsUpdateScanCompletedEventArgs const&) noexcept = default;
        IWindowsUpdateScanCompletedEventArgs(IWindowsUpdateScanCompletedEventArgs&&) noexcept = default;
        IWindowsUpdateScanCompletedEventArgs& operator=(IWindowsUpdateScanCompletedEventArgs const&) & noexcept = default;
        IWindowsUpdateScanCompletedEventArgs& operator=(IWindowsUpdateScanCompletedEventArgs&&) & noexcept = default;
    };
}
#endif
